# 09_메서드에 예외 선언하기
> 예외를 처리하는 방법에는 지금까지 배워 온 `try-catch문`을 사용하는 것 외에,
`예외를 메서드에 선언하는 방법`이 있다.
메서드에 예외를 선언하려면, `메서드의 선언부`에 키워드 `throws를 사용`해서 `메서드 내에 발생할 수 있는 예외를 적어`주기만 하면 된다.
> 

```java
void method() throws Exception1, Exception2, ... ExceptionN  {
			// 메서드의 내용
}
```

💢 **참고** : **예외를 발생시키는 키워드 throw**와 **예외를 메서드에 선언할 때 쓰이는 throws**를 잘 구별하기!

- 만약 아래와 같이 모든 예외의 최고 조상인 Exception클래스를 메서드에 선언하면,
이 메서드는 모든 종류의 예외가 발생할 가능성이 있다는 뜻이다.

```java
void method() throws Exception {
			// 메서드의 내용
}
```

- **오버라이딩 할 때는 단순히 선언된 예외의 개수가 아니라 상속관계까지 고려해야 한다.**
- 메서드의 선언부에 예외를 선언함으로써 메서드를 사용하는 사람이 메서드의 선언부를 보았을 때,
- 이 메서드를 사용하기 위해서는 어떠한 예외들이 처리되어져야 하는지 쉽게 알 수 있다.
- 기존의 많은 언어들에서는 메서드에 예외선언을 하지 않기 때문에,
- 경험 많은 프로그래머가 아니고서는 어떤 상황에 어떤 종류의 예외가 발생할지 몰랐다.
- 그러나 자바에서는 메서드를 작성할 때 발생 가능성이 있는 예외를 선언부에 같이 명시하므로
- 메서드를 사용하는 쪽에서는 이에 대한 처리를 강요하도록 하기 때문에 프로그래머들의 짐을 덜어주고 보다 견고한 프로그램 코드를 작성할 수 있게 도와준다.

## 메서드에 예외 선언하기 예제_1

```java
public class Ex8_9 {
    public static void main(String[] args) throws Exception {
        method1(); // 같은 클래스 내의 static멤버이므로 객체 생성 없이 직접 호출 가능.
    }   // main메서드의 끝

    static void method1() throws Exception {
        method2();
    }   // method1의 끝

    static void method2() throws Exception {
        throw new Exception();
    }   // method2의 끝
}
```

**컴파일 결과**

```java
Exception in thread "main" java.lang.Exception
	at exception_handling.Ex8_9.method2(Ex8_9.java:13)
	at exception_handling.Ex8_9.method1(Ex8_9.java:9)
	at exception_handling.Ex8_9.main(Ex8_9.java:5)
```

- method2()에서 throw new Exception(); 문장에 의해 예외가 강제적으로 발생했으나,
- try-catch문으로 예외처리를 해주지 않았으므로, method2()는 종료되면서 자신을 호출한 method1()에게 예외를 넘겨준다.
- method1()에서도 역시 예외 처리를 해주지 않았으므로 종료되면서 main메서드에게 예외를 넘겨준다.
- 그러나 main메서드에서도 예외처리를 해주지 않아 main메서드가 종료되어 프로그램이 예외로 인해 비정상적으로 종료.
- 이처럼 예외가 발생한 메서드에서 예외처리를 하지 않고 자신을 호출한 메서드에게 예외를 넘겨줄 수는 있지만,
- 이것으로 예외가 처리된 것이 아니고 단순히 전달만 하는 것이기 때문에 결국 어느 한 곳에서는 반드시
try-catch문으로 예외 처리를 해줘야 한다.

### 💢참고

```java
public static void main(String[] args) throws Exception {
        method1(); // 같은 클래스 내의 static멤버이므로 객체 생성 없이 직접 호출 가능.
    }
```

- throws Exception 처럼 예외가 선언되어 있으면 Exception과 같은 체크드(checked) 예외를 꼭 try-catch문으로 처리하지 않아도 컴파일 에러는 발생하지 않는다!

## 메서드에 예외 선언하기 예제_2

```java
public class Ex8_10 {
    public static void main(String[] args) {

        try {
            File f = createFile("test.txt");
            System.out.println(f.getName()+"파일이 성공적으로 생성되었습니다.");
        } catch (Exception e) {
            System.out.println(e.getMessage()+"다시 입력해주세요.");
        }
    }   // main메서드의 끝

    static File createFile(String fileName) throws Exception {
        if (fileName==null || fileName.equals(""))
            throw new Exception("파일 이름이 유효하지 않습니다.");

        File f = new File(fileName);    // File클래스의 객체를 만든다.

        // File객체의 createNewFile메서드를 이용해서 실제 파일을 생성한다.
        f.createNewFile();

        return f;   // 생성된 객체의 참조를 반환한다.

    }   // createFile메서드의 끝
}   // 클래스의 끝
```

**예외 발생❌  컴파일 결과**

```java
// File f = createFile("test.txt");

test2.txt파일이 성공적으로 생성되었습니다.
```

**예외 발생⭕️ 컴파일 결과**

```java
// File f = createFile("");
파일 이름이 유효하지 않습니다.다시 입력해주세요.
```

> 다음은 사용자로부터 파일 이름을 입력받아서 파일을 생성하는 예제이다.
파일을 생성하는 것은 createFile()인데, 이 메서드는 입력받은 파일의 이름이 유효하지 않으면 예외를 발생시킨다.
> 
1. try문에서 createFile 메서드를 호출한다.
2. 해당 메서드에서 if문에 해당사항이 없으면 정상적으로 파일을 생성하여 리턴한다.
3. 만일 파일 이름이 null이거나 “”빈 문자열이라면 Exception이 선언되어 메인 메서드로 넘겨진다.
4. 그럼 main메서드에서 넘겨받은 Exception을 try-catch로 처리하게 되는데 catch문에서 Exception의 생성자 안에 내용을 getMessage()로 불러온 것이다.
